### ISSUE TITLE
Error in Seurat velocyto wrapper after  fastq to loom command-line tool

### ISSUE THREAD

**Issue by ChaDuss** [linnarsson-lab/loompy#122]
Hello loompy team,
I have created loom file from fastq 10x genomics datas with your command line tool.
After that i've tried to use the loom file with seurat velocyto wrapper, unfortunately the ReadVelocity command retrun this error : 
Error in `[[.H5File`(f, path) : 
  An object with name layers/ambiguous does not exist in this group
Do you know how i can deal with it ?
Thank you for your answer and happy new year !

**Comment by slinnarsson** [comment]
Hi

Loompy fromfq doesn’t ceate an ”ambiguous” layer. Just make a dummy empty layer, or ask the Seurat maintainers to remove the dependency on this layer.

Best

Sten


--

Sten Linnarsson, PhD
Professor of Molecular Systems Biology
Karolinska Institutet
Unit of Molecular Neurobiology
Department of Medical Biochemistry and Biophysics
Biomedicum C6
Tomtebodavägen 16, 171 77 Stockholm, Sweden
+46 70 399 32 06 (mobile)
________________________________
Från: ChaDuss <notifications@github.com>
Skickat: Tuesday, December 31, 2019 1:57:51 PM
Till: linnarsson-lab/loompy <loompy@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [linnarsson-lab/loompy] Error in Seurat velocyto wrapper after fastq to loom command-line tool (#122)


Hello loompy team,
I have created loom file from fastq 10x genomics datas with your command line tool.
After that i've tried to use the loom file with seurat velocyto wrapper, unfortunately the ReadVelocity command retrun this error :
Error in [[.H5File(f, path) :
An object with name layers/ambiguous does not exist in this group
Do you know how i can deal with it ?
Thank you for your answer and happy new year !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flinnarsson-lab%2Floompy%2Fissues%2F122%3Femail_source%3Dnotifications%26email_token%3DACRJVAZLT4CEGSHEBWXDEWLQ3M6U7A5CNFSM4KBVLBCKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IDPST3Q&data=02%7C01%7Csten.linnarsson%40ki.se%7Cd695792b90fc4ed0f7fc08d78df10d70%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637133938763840895&sdata=VpqNd9poBKa5N6e3mQrdZrBOi8kG9ewNR4dq1cHeFiw%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACRJVA7YMCJQROMAQGTZG3DQ3M6U7ANCNFSM4KBVLBCA&data=02%7C01%7Csten.linnarsson%40ki.se%7Cd695792b90fc4ed0f7fc08d78df10d70%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637133938763850885&sdata=JePO6Gwfhe%2FNa33rGrwsmM0DLR%2BlAOz8hXMDhxt2mZ8%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by ChaDuss** [comment]
Thank you for your answer.

Best

Charles

Le mar. 31 déc. 2019 à 21:35, Sten Linnarsson <notifications@github.com> a
écrit :
