### ISSUE TITLE
Memory issue when creating a loom file from a sparse matrix

### ISSUE THREAD

**Issue by wkopp** [linnarsson-lab/loompy#134]
Hi,

I'd like to create a loom file from a sparse matrix, but run into memory issues.

I have a sparse matrix

```
>>> mat
<1345115x23008 sparse matrix of type '<class 'numpy.int64'>'
	with 228111079 stored elements in Compressed Sparse Row format>
```

running loompy gives the following error
```
>>> loompy.create('test.loom', mat, rowannot, colannot)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/loompy/loompy.py", line 1058, in create
    ds.layer[""] = layers[""]
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/loompy/layer_manager.py", line 90, in __setitem__
    return self.__setattr__(name, val)
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/loompy/layer_manager.py", line 156, in __setattr__
    self.ds._file[path][:, ix:ix + window] = m[:, ix: ix + window].toarray()
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 1025, in toarray
    out = self._process_toarray_args(order, out)
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/scipy/sparse/base.py", line 1185, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError: Unable to allocate 64.1 GiB for an array with shape (1345115, 6400) and data type int64
```

Looking into the code, it seems that the reason for the issue is that the matrix is column block-wise unpacked. But since, my row dimensions are rather large, I nevertheless have memory issues.

Perhaps, one way around this might be to check which dimensions (rows or columns) are larger and then perform the unpacking accordingly. Or to adjust the block size dynamically such that the memory requirement for the block is below some threshold, instead of using a fixed block size of 6400 elements.

Do you think this is worth a pull request?

Best,
Wolfgang

**Comment by slinnarsson** [comment]
Sure, makes sense.

Sten


--

Sten Linnarsson, PhD
Professor of Molecular Systems Biology
Karolinska Institutet
Unit of Molecular Neurobiology
Department of Medical Biochemistry and Biophysics
Biomedicum C6
Tomtebodavägen 16, 171 77 Stockholm, Sweden
+46 70 399 32 06 (mobile)
________________________________
Från: Wolfgang Kopp <notifications@github.com>
Skickat: Tuesday, July 28, 2020 5:41:46 PM
Till: linnarsson-lab/loompy <loompy@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [linnarsson-lab/loompy] Memory issue when creating a loom file from a sparse matrix (#134)


Hi,

I'd like to create a loom file from a sparse matrix, but run into memory issues.

I have a sparse matrix

>>> mat
<1345115x23008 sparse matrix of type '<class 'numpy.int64'>'
        with 228111079 stored elements in Compressed Sparse Row format>


running loompy gives the following error

>>> loompy.create('test.loom', mat, rowannot, colannot)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/loompy/loompy.py", line 1058, in create
    ds.layer[""] = layers[""]
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/loompy/layer_manager.py", line 90, in __setitem__
    return self.__setattr__(name, val)
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/loompy/layer_manager.py", line 156, in __setattr__
    self.ds._file[path][:, ix:ix + window] = m[:, ix: ix + window].toarray()
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 1025, in toarray
    out = self._process_toarray_args(order, out)
  File "/home/wkopp/anaconda3/envs/scregseg/lib/python3.7/site-packages/scipy/sparse/base.py", line 1185, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
MemoryError: Unable to allocate 64.1 GiB for an array with shape (1345115, 6400) and data type int64


Looking into the code, it seems that the reason for the issue is that the matrix is column block-wise unpacked. But since, my row dimensions are rather large, I nevertheless have memory issues.

Perhaps, one way around this might be to check which dimensions (rows or columns) are larger and then perform the unpacking accordingly.

Do you think this is worth a pull request?

Best,
Wolfgang

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flinnarsson-lab%2Floompy%2Fissues%2F134&data=02%7C01%7Csten.linnarsson%40ki.se%7C5a0af8a41275474138ee08d8330cbd6a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637315477098035492&sdata=Nwqw26ri%2FTHDuijmXWcJZ4bbdDR5JKFccXqIbpimr0I%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACRJVA22YNUYPSBSLVDKIS3R53WTVANCNFSM4PKU6FBA&data=02%7C01%7Csten.linnarsson%40ki.se%7C5a0af8a41275474138ee08d8330cbd6a%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637315477098045489&sdata=CGoWknYATGTFRx5y40Bs%2FVQe%2B870jXCcIZznbCpxnEU%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI’s processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by jacksonloper** [comment]
for super-sparse matrices, it seems like loom would need to natively support CSR representations of the data.  any plans to support this?  atacseq data (i've seen datasets with 400,000 nontrivial peaks (!)) would be one application where i think it would make a big difference.

**Comment by slinnarsson** [comment]
Unfortunately I think we won't be working on that. I realize that Loom doesn't support ATAC-seq data well, and it also doesn't work well for image-based data (smFISH, Visium etc). But it will require a rethinking of the whole data model, and probably a non-compatible successor to Loom to do this properly.
