### ISSUE TITLE
Match behaviour of closing LoomConnection with regular file API behaviour

### ISSUE THREAD

**Issue by JobLeonard** [linnarsson-lab/loompy#15]
Just a quick check if these API updates are approved before I push them to GitHub:

Normal file connections have a read-only `closed` Bool variable that the user can read to check if the file is closed. Added this to `LoomConnection` too. Basically, `self._closed` is set to false by `__init__`, and to true by `close()`, and accessible through a `closed` getter:

```python
	@property
	def closed(self) -> Bool:
		return self._closed
```

Currently, calling `ds.close()` on an already closed connection raises an error because it calls `self._file.close()` after setting `self._file` to none.

I'm somewhat on the fence on this one, since throwing an error could arguably be considered the right behaviour (telling the programmer to not call `close()` superfluously). 

OTOH, trying to close an already closed connection is harmless, and very annoying if it interrupts a long-running script. Also, calling `f.close()` twice on a regular file does nothing, so that's apparently the Pythonic way that users will expect.

The lack of feedback is a bit stupid IMO, so as a compromise I added a check + a warning for now:

```python
	def close(self) -> None:
		"""
		Close the connection. After this, the connection object becomes invalid.
		"""
		if self._file is None:
			# Warn user that they're being paranoid and should clean up their code
			logging.warn("Connection to %s is already closed", self.filename)
		else:
			self._file.close()
			self._file = None
		self.row_attrs = {}
		self.col_attrs = {}
		self.shape = [0, 0]
		self.closed = true
```

Finally, I wrapped `__init__` in a `try/except` block to ensure we properly close the h5py connection in case it fails on bad input (semi-related to issue #10):

```python
		try:
			# old initialisation code
		except e:
			logging.warn("construction LoomConnection to %s failed, closing file connection", filename)
			self.close()
			raise e
```

**Comment by slinnarsson** [comment]
Yes, looks like a good idea.



Skickat från min iPhone

3 nov. 2017 kl. 16:18 skrev Job van der Zwan <notifications@github.com<mailto:notifications@github.com>>:


Just a quick check if these API updates are approved before I push them to GitHub:

Normal file connections have a read-only closed Bool variable that the user can read to check if the file is closed. Added this to LoomConnection too. Basically, self._closed is set to false by __init__, and to true by close(), and accessible through a closed getter:

        @property
        def closed(self) -> Bool:
                return self._closed

Currently, calling ds.close() on an already closed connection raises an error because it calls self._file.close() after setting self._file to none.

I'm somewhat on the fence on this one, since throwing an error could arguably be considered the right behaviour (telling the programmer to not call close() superfluously).

OTOH, trying to close an already closed connection is harmless, and very annoying if it interrupts a long-running script. Also, calling f.close() twice on a regular file does nothing, so that's apparently the Pythonic way that users will expect.

The lack of feedback is a bit stupid IMO, so as a compromise I added a check + a warning for now:

        def close(self) -> None:
                """
                Close the connection. After this, the connection object becomes invalid.
                """
                if self._file is None:
                        # Warn user that they're being paranoid and should clean up their code
                        logging.warn("Connection to %s is already closed", self.filename)
                else:
                        self._file.close()
                        self._file = None
                self.row_attrs = {}
                self.col_attrs = {}
                self.shape = [0, 0]
                self.closed = true

Finally, I wrapped __init__ in a try/except block to ensure we properly close the h5py connection in case it fails on bad input (semi-related to issue #10<https://github.com/linnarsson-lab/loompy/issues/10>):

                try:
                        # old initialisation code
                except e:
                        logging.warn("construction LoomConnection to %s failed, closing file connection", filename)
                        self.close()
                        raise e

**Comment by slinnarsson** [comment]
Maybe even better would be to support a ”with” syntax:

with loompy.connect(filename) as ds:
    ....do something

And the file is closed automatically.

**Comment by JobLeonard** [comment]
Sure, will look up what is required for that!

**Comment by JobLeonard** [comment]
Added:
![image](https://user-images.githubusercontent.com/259840/32562008-ef8a788e-c4ad-11e7-8bb1-3a5a04eca604.png)

Note that I also made `__repr_html__` check if the connection is closed or not. When close it will now print `This LoomConnection has been closed`, instead of crashing
