### ISSUE TITLE
Memoization

### ISSUE THREAD

**Issue by slinnarsson** [linnarsson-lab/loompy#18]
Support memoization of access to the full matrix, using [weakref](https://docs.python.org/3/library/weakref.html) to avoid hogging RAM.

This will allow repeated loading of the full matrix without repeated access to disk. Use-case is especially stringing together methods from multiple packages:

```python
seurat = robjects.r['seurat']
pagoda = robjects.r['pagoda']
with loompy.connect("filename.loom") as ds:
    scanpy.api.pp.filter_cells(ds)
    cytograph.multiscale_knn(ds)
    seurat.cluster(ds)
    pagoda.diff_expression(ds)
```

Need to keep track of when the matrix changes either by writing or by adding columns.

**Comment by JobLeonard** [comment]
I've been trying to get HDF5 chunk caching to behave as promised in the HDF5 docs, to no avail (and if we could get ut to work as promised it would also reduce some of the need for this).

The reason I'm bringing this up is because for large datasets, if I didn't watch out I would hit the limits of available RAM, and it turns out that python has *no* problems with loading an HDF5 matrix from disk into a numpy matrix that is stored in swap.. which is the disk.

This would completely freeze my laptop, even with the high end specs I have. 

Do you have any ideas on whether we could automatically avoid this scenario here? I guess we'd need some kind of way of detecting available RAM and limiting the memoization accordingly.

**Comment by slinnarsson** [comment]
I don't think it's possible to know how much real RAM is available. It's very subtle on modern OSs (e.g. Mac OS will compress data in RAM, and may then uncompress it as needed). But memoization using weakref should at least not be worse than just loading the whole matrix. The user would anyway have to be sure the data fits.

We should support memoization of dense as well as sparse data.

**Comment by slinnarsson** [comment]
Let’s not over-complicate this. The only interesting use-case is loading the whole matrix, as dense or sparse. Any other more complex access pattern is unlikely to recur. 

I don’t see how the user-defined upper limit helps. If we’re asking the user to tell us what the max size of the dataset is, why not just trust her to know that and not load the dataset when it’s too large?

**Comment by JobLeonard** [comment]
Wait, I'm a bit confused then: what is the kind of caching that takes place here then, and how is it different from loading the entire matrix as a giant numpy array?

**Comment by slinnarsson** [comment]
I'm closing this now as probably not worth the effort.
