### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by mojaveazure** [linnarsson-lab/loompy#2]
I'm trying to use loompy, but it fails to load. I've installed it using pip3 (`pip3 install loompy`). When I import it, I get the following error.

```python
>>> import loompy
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import loompy
  File "/home/paul/.local/lib/python3.5/site-packages/loompy/__init__.py", line 1, in <module>
    from .loompy import connect, create, combine, create_from_cellranger, LoomConnection
  File "/home/paul/.local/lib/python3.5/site-packages/loompy/loompy.py", line 942
    data: np.ndarray = None
        ^
SyntaxError: invalid syntax
```

I'm currently using Python 3.5.2 under Ubuntu 16.04.3

```bash
$ python3 --version
Python 3.5.2
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by slinnarsson** [comment]
You need Python 3.6 to run loompy, because we use type annotations.

Sten

--
Sten Linnarsson, PhD
Professor of Molecular Systems Biology
Karolinska Institutet
Unit of Molecular Neurobiology
Department of Medical Biochemistry and Biophysics
Scheeles väg 1, 171 77 Stockholm, Sweden<x-apple-data-detectors://1/0>
+46 8 52 48 75 77<tel:+46%208%2052%2048%2075%2077> (office)
+46 70 399 32 06<tel:+46%2070%20399%2032%2006> (mobile)

19 okt. 2017 kl. 00:00 skrev Paul Hoffman <notifications@github.com<mailto:notifications@github.com>>:


I'm trying to use loompy, but it fails to load. I've installed it using pip3 (pip3 install loompy). When I import it, I get the following error.

>>> import loompy
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import loompy
  File "/home/paul/.local/lib/python3.5/site-packages/loompy/__init__.py", line 1, in <module>
    from .loompy import connect, create, combine, create_from_cellranger, LoomConnection
  File "/home/paul/.local/lib/python3.5/site-packages/loompy/loompy.py", line 942
    data: np.ndarray = None
        ^
SyntaxError: invalid syntax

I'm currently using Python 3.5.2 under Ubuntu 16.04.3

$ python3 --version
Python 3.5.2
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
