### ISSUE TITLE
Error with loompy.combine for Velocyto output files

### ISSUE THREAD

**Issue by dpcook** [linnarsson-lab/loompy#30]
Hi all,

I have four loom files outputted from separate Velocyto (0.13.4) runs (a time course experiment done with multiple 10x runs) that I'm trying to combine into a single loom file to run through Velocyto's analysis pipeline.

`files = ['/path/to/file_1.loom', '/path/to/file_2.loom', '/path/to/file_3.loom', '/path/to/file_4.loom']`
`loompy.combine(files, '/path/to/merged_files.loom')`
KeyError: "Unable to open object (object 'layersambiguous' doesn't exist)"

However, I can connect to each loom file with no apparent issues:

`df = loompy.connect('/path/to/file_1.loom')`
`df`
33694 rows, 3372 columns, 4 layers
(showing up to 10x10)
/global/scratch/hpc3837/cellranger-count/Control/velocyto/Control.loom
name: 20180129T231506.293015Z
name: 2018/01/29 18:15:06
name: 0.13.4

I'm sure I'm just missing something straight forward. Any help is much appreciated!

David

**Comment by slinnarsson** [comment]
Can you paste the full stack trace? It will help me locate the error.

**Comment by slinnarsson** [comment]
With the help of @gioelelm I think I located the bug, which I had accidentally introduced when implementing timestamps per #26. 

I also pushed a new release v2.0.3 to PyPi so that you will be able to `pip install -U loompy` to get the fixes installed. It may take a little time to percolate through the PyPi servers so please check that you are getting v2.0.3 and not anything older.

Let me know if this fixes the issue

**Comment by dpcook** [comment]
Hi Sten and @gioelelm 

Morning from Canada--sorry about not getting the error message to you sooner. I updated to v2.0.3 and the error was resolved. Thank you for the quick support!

David

**Comment by slinnarsson** [comment]
Great to hear it worked!
