### ISSUE TITLE
Specification question: which specific "string" type do you use?

### ISSUE THREAD

**Issue by shoyer** [linnarsson-lab/loompy#4]
Strings are not so simple in HDF5. You can ASCII or UTF-8 encoding and fixed or variable length -- see h5py for a summary: http://docs.h5py.org/en/latest/strings.html

Which do you use? This is an important sort of detail to clarify in the spec.

**Comment by JobLeonard** [comment]
The `loompy` the library has a policy of encoding everything in fixed-length ASCII.

For example, this is what we currently have in the source code regarding the saving/loading of attributes, at [line 158](https://github.com/linnarsson-lab/loompy/blob/master/loompy/loompy.py#L158):

```python
	def _save_attr(self, name: str, values: np.ndarray, axis: int) -> None:
		"""
		Save an attribute to the file, nothing else

		Remarks:
			Handles unicode to ascii conversion (lossy, but HDF5 supports only ascii)
			Does not update the attribute cache (use _load_attr for this)
		"""
		if self.mode != "r+":
			raise IOError("Cannot save attributes when connected in read-only mode")
		if values.dtype.type is np.str_:
			values = np.array([x.encode('ascii', 'ignore') for x in values])

		a = ["/row_attrs/", "/col_attrs/"][axis]
		if self.shape[axis] != 0 and len(values) != self.shape[axis]:
			raise ValueError("Attribute must have exactly %d values" % self.shape[axis])
		if self._file[a].__contains__(name):
			del self._file[a + name]
		self._file[a + name] = values
		self._file.flush()

	def _load_attr(self, name: str, axis: int) -> None:
		"""
		Load an attribute from the file, nothing else

		Remarks:
			Handles ascii to unicode conversion
			Updates the attribute cache as well as the class attributes
		"""
		a = ["/row_attrs/", "/col_attrs/"][axis]

		def safe_decode(s: np.bytes_) -> str:
			try:
				return s.decode('utf8')
			except UnicodeDecodeError:
				return "[UTF-8 DECODING ERROR]"

		if self._file[a][name].dtype.kind == 'S':
			vals = np.array([safe_decode(x) for x in self._file[a][name][:]])
		else:
			vals = self._file[a][name][:]

		if axis == 0:
			self.row_attrs[name] = vals
			if not hasattr(LoomConnection, name):
				setattr(self, name, self.row_attrs[name])
		else:
			self.col_attrs[name] = vals
			if not hasattr(LoomConnection, name):
				setattr(self, name, self.col_attrs[name])
```

I guess the comment about HDF5 only supporting ASCII is _technically_ incorrect, but the idea is to be maximally compatible with other platforms. As per the docs you linked:

> In the file, these map to fixed-width ASCII strings. One byte per character is used. The representation is “null-padded”, which is the internal representation used by NumPy (and the only one which round-trips through HDF5).
>
> Technically, these strings are supposed to store only ASCII-encoded text, although in practice anything you can store in NumPy will round-trip. But for compatibility with other progams using HDF5 (IDL, MATLAB, etc.), you should use ASCII only.

I don't know if the spec should also reflect that though, that's up to Sten to decide.

**Comment by slinnarsson** [comment]
I have fought this battle and lost. I would love for the spec to be "UTF8" variable-length strings. However, this doesn't work with numpy in Python. 

So, for now, we stick with ASCII fixed-width strings.

**Comment by shoyer** [comment]
>  I would love for the spec to be "UTF8" variable-length strings. However, this doesn't work with numpy in Python.

I'm not sure I agree here. It's true that NumPy doesn't have a native UTF-8 type, but NumPy's string dtypes are not very practical, especially on Python 3. In most cases, using an object array of native Python strings (what pandas uses) is the most practical choice.

**Comment by JobLeonard** [comment]
I will refrain from commenting on what is practical within Python, since I don't work in that space very often.

The `h5py` documentation cited earlier suggesting ASCII is the best option for cross-platform compatibility has me more concerned. So I had a quick look at the docs for HDF5 wrappers Matlab and R (since those seem to be the most common SciPy alternatives in this particular field). The results are a bit frustrating:

MATLAB: [utf8 is supported](https://se.mathworks.com/help/matlab/ref/h5create.html). In fact, it is the only other choice next to using the system default, which sounds like it could break between computers (since various systems might use different defaults):
![image](https://user-images.githubusercontent.com/259840/32236511-ac41314a-be62-11e7-8973-3fb9a2a2a822.png)

R ([Bioconductor rhdf5](http://bioconductor.org/packages/release/bioc/html/rhdf5.html)): [seems to not be supported yet?](http://bioconductor.org/packages/release/bioc/manuals/rhdf5/man/rhdf5.pdf#Rfn.h5write.1). @LTLA might know more?
![image](https://user-images.githubusercontent.com/259840/32236884-bb5bb384-be63-11e7-8ec3-bad0859d91d1.png)

So with Matlab we might risk getting some weird Windows encoding that does not play nice with Mac encoding, or the other way around, and with R we *can't* choose UTF-8 yet, even if we wanted to.

If R would add support for UTF-8 it would be preferable as the more reliable format. For now ASCII seems to be the... well, let's call it "least unreliable" option.

(aside: had a quick look at potential alternative *server* languages for the loom-viewer, which would need the ability to read from HDF5 files. I'm not going to consider C++ or C code for this, too easy to shoot yourself in the foot. [`gonum/hdf5`](https://github.com/gonum/hdf5) currently [only supports c-strings](https://godoc.org/gonum.org/v1/hdf5#NewDatatype) (so ASCII), which is ironic because Go itself uses UTF-8 strings by default. [Julia supports utf8](https://github.com/JuliaIO/HDF5.jl/blob/master/doc/hdf5.md#supported-data-types), and is basically a faster (and more beautiful) SciPy, so it might be worth looking into at some future date when the language and libraries stabilise a bit. And apparently there is [a `node.js` package for HDF5](https://github.com/HDF-NI/hdf5.node), so [Atwood's law strikes again](https://blog.codinghorror.com/the-principle-of-least-power/)! ... impressive, but no thanks).

**Comment by slinnarsson** [comment]
After a lot of fiddling around and thinking about the best compromise, here's what I came up with:

1. All attributes are stored in HDF5 as arrays of fixed-width ASCII strings (or float64 for numbers). This is unchanged.

2. If the input contains unicode strings, any non-ascii characters are [XML entity encoded](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references). E.g. `25 µl` is written as the ascii string `25 &#181;l` to the HDF5 file. 

3. When read back, any XML entities are unescaped, so that you get the original back. 

4. This is all transparent to the Python user: you work with unicode arrays and nevermind how they are stored. At the same time, it ensures interoperability with languages that do not support unicode in HDF5 (such as MATLAB).

This adds support for Unicode to Loom, while maintaining ASCII-only storage for compatibility with MATLAB and other languages that don't understand Unicode. It adds a small burden to implementors of Loom readers: you will have to call the equivalent of `html.unescape(x)` on the ascii strings.
