### ISSUE TITLE
sparse data overhead -- 3.9 GB inflated to 9.0 GB

### ISSUE THREAD

**Issue by jeff-regier** [linnarsson-lab/loompy#49]
I used the script posted in issue #48 to convert a large, sparse 10x dataset ("1M_neurons_filtered_gene_bc_matrices_h5.h5"). The input file from 10x is 3.9 GB, and the data matrix is sparse -- about 4% fill, I think. The output `.loom` file is 9.0 GB. Are there any flags or options I can specify that will make the output file size smaller? Maybe larger chunks to better exploit the sparsity? Or shuffling the columns and rows somehow to get more "all zero" chunks? Or are there any compression algorithms that are better than gzip for sparse data?

Thanks!

**Comment by slinnarsson** [comment]
An easy change is to use `int16` (two bytes) instead of `float32` (4 bytes) to store the data. It will only reduce the file size slightly, though, because float32 compresses much better (since the two high-order bytes are mostly zeros). 

Another possibility is to sort the rows (genes) by expression level, so that the bottom half or so of the matrix is all zeros. That's probably a major win, but you'd first have to create the file. Something like this (not tested):

```
with loompy.connect("1M_cells.loom") as ds:
    nnz = ds.map([np.count_nonzero], axis=1)[0]
    ordering = np.argsort(-nnz)
    ds.permute(ordering, axis=0)
```

After this, you'd probably have to copy the data over to a new file (i.e. using `ds.scan()`) to force HDF5 to reclaim the space gained by the improved compression.

We use a chunk size of (64, 64) which was optimized for speed, not compression. It's possible that larger chunk sizes could be more efficiently compressed, but at the expense of slower access (especially random accesss of individual rows or columns, which needs to load entire chunks along one axis). There are also other compression methods than gzip, but only gzip is supported widely so you'd risk creating files that could not be read on all platforms. 

On the upside, 1.3 million cells in 9 GB is not too shabby, considering that even laptops have terabytes of disk these days! You'll be able to fit every single-cell experiment ever published on a 64 USB stick.

**Comment by jeff-regier** [comment]
Thanks for another thoughtful response, Sten. Sorting the rows (genes) by expression level sounds like a great idea...might even get the output smaller than the input file.

The reason I'm concerned about file size is that I'm developing an iterative algorithm that requires several hundreds passes over multiple datasets, including the large one from the 10x. I'd like to avoid ever storing any entire dataset in memory at once. So that means reading them all from disk several hundred times. I'm aiming to keep the I/O time low enough that the program remains compute bound. I think the loom format may work well for that. Thanks again for your response, and for your work on loompy!

**Comment by slinnarsson** [comment]
This is exactly how our cytograph pipeline works. We use out-of-RAM algorithms and scan across the columns using the scan() method. Look in the cytograph repo, for example manifold_learning2.py, for some examples. 

With this approach, I can analyze millions if cells on my laptop. It’s a little slower than in-RAM of course, but it scales to any size datasets. Rahul Satija has implemented this approach in his latest Seurat package, also based on Loom.
