### ISSUE TITLE
Providing support for loom files in R/Bioconductor

### ISSUE THREAD

**Issue by LTLA** [linnarsson-lab/loompy#6]
Some of us in Bioconductor are exploring the compatibility of `*.loom` files with our existing HDF5 data architecture. It seems feasible (potentially trivially so) based on examination of the specifications, but is it possible to obtain some actual `*.loom` files to play around with? I can't figure out where  `cortex.loom` comes from in the example code, and https://loom.linnarssonlab.org/ doesn't seem to be functional.

**Comment by JobLeonard** [comment]
[Here is an "unofficial" link to the `cortex.loom` file](https://www.dropbox.com/s/xjk5nnyw8ymjjck/cortex.loom?dl=0), from my dropbox (we should probably upload it to the documentation website, so it can be statically linked from the docs). Hope this is enough for you to test it in practice with.

Of course, you could also create a few `.loom` files yourself with `loompy` ;)

The data is from the [_Cell types in the mouse cortex and hippocampus revealed by single-cell RNA-seq_ 
 paper from 2015](http://science.sciencemag.org/content/347/6226/1138) ([Linnarsson Lab page with additional data](http://linnarssonlab.org/cortex/))

Note: I'm not entirely sure if it is _all_ the data - it is a very old file, back from when our pipeline was more buggy then now, and I believe the backspin metadata attributes did get transcribed correctly, for example. So it might not perfectly match up with the data you can get from Science or the linked website.

It also does not have the optional `/layers` subgroup [mentioned in the specification](http://loompy.org/loompy-docs/format/index.html#specification), since it pre-dates our usage of it.

Regarding the website: we had been using https://loom.linnarssonlab.org/ internally, including for not-yet-published research. So it's temporarily offline until the published/unpublished datasets are separated, and we put the unpublished ones somewhere else, preferably behind a password ;). Our apologies for the inconvenience.

**Comment by LTLA** [comment]
Sweet, thanks. As I had hoped, it was indeed trivially compatible; check out my efforts here:

https://github.com/LTLA/HumanCellAtlasData/blob/master/inst/scripts/make-data.R

... in the `loom2sce` function. The `layers` part of the code is not tested, I just put in my best guess.
