### ISSUE TITLE
Error when installing: Typo in setup.py

### ISSUE THREAD

**Issue by stefanpeidli** [linnarsson-lab/loompy#64]
Hey everyone,
I had problems installing loompy. I think I found a small Typo in your Code for setup.py in line 26
`download_url=f"https://github.com/linnarsson-lab/loompy/archive/{__version__}.tar.gz"`
After deleting this "f" in front of the url it worked for me. Is this a typo or is it relevant in any way?

**Comment by mschilli87** [comment]
My guess is you are on an old python version. Literal string interpolation [is a new feature since 3.6](https://www.python.org/dev/peps/pep-0498/) and afaik not the only one that is used by loompy. So even if you manage to install it by hacking the source, you probably won't be able to run loompy successfully without using python >=3.6.

**Comment by stefanpeidli** [comment]
That was the problem: I used Python 3.5. Thanks!
