### ISSUE TITLE
ASCII vs UTF-8 and variable String length

### ISSUE THREAD

**Issue by VincentGardeux** [linnarsson-lab/loompy#93]
Hey,

I stumbled upon two errors with my self-generated Loom file.
- UTF-8 Strings are not supported.
- variable length Strings are not supported

The first error can easily be fixed, and does not have a huge impact (except for storing fancy characters). However, the second point is more problematic (especially for storage purpose). Because, in my file, Strings can be very long sometimes, and thus creating non-variable length Strings make the Loom file explode in size (the annotations are taking way more storage than the actual matrix, for a file that is growing beside Gb, while the matrix alone is only a few Mb)

I saw an exchange from 2017 on Github, discussing this issue. But I wonder if this spec is still necessary, as it really can make the size of the Loom way bigger than required, for no apparent reason)

Thanks

**Comment by slinnarsson** [comment]
Hi - this sounds reasonable and I'll look into it. Some of the restrictions on the spec are there to simplify implementations. I.e. if we needed to support every possible datatype that's valid HDF5, then each loom implementation would also need to ensure it could roundtrip data to/from every possible datatype. It gets pretty challenging for strings in particular, since there are so many ways to represent them both in HDF5 and in each programming language. I wish everything could just be variable-length UTF-8 and I'll see if we could make this happen.

But variable-length strings sounds reasonably easy to do.

As for storing UTF-8, the currently supported method is to use XML entity encodings and store as ASCII. No need to lose your fancy characters!

**Comment by slinnarsson** [comment]
Tentatively fixed in loompy3.0 branch
